name: Upload JSON to GitHub

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  upload-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Update to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Update to v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client

      - name: Run the Python script
        env:
          SERVICE_ACCOUNT_FILE: ${{ secrets.SERVICE_ACCOUNT_FILE }}
        run: |
          python fetch_gspread_data.py

      - name: Commit and push JSON file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add forbes_blog_data.json
          git commit -m "Update JSON data"
          git push
